/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>
#include <stdint.h>
#include "stm32l476xx.h"
#include "gpio.h"



GPIO_Handle_t tUltraSonicGpio;
uint8_t ucTriggerPIn = eGPIO_PIN_9;
uint8_t ucEchoPin = eGPIO_PIN_10;


void InitUltraSonicSensor(void);
uint32_t ReadUltraSonicSensor(void);

void Delay(uint32_t uiMs)
{
	unsigned int i = 0, j= 0;
	for(i = 0; i < uiMs; ++i)
	{
		for(j = 0; j < 600; ++j);
	}
}

void delay_us(uint32_t us) {
    // This value MUST BE CALIBRATED for your specific clock speed!
    // For an STM32L476 running at a few MHz, this might be close.
    // For 16MHz, try a value around 4-6. For 80MHz, try around 30.
    volatile uint32_t cycles = us * 4;
    for(; cycles > 0; cycles--);
}

void InitLed(void);
void TestLed(void);

int main(void)
{
	InitLed();
	InitUltraSonicSensor();
	while(1)
	{
		if(ReadUltraSonicSensor() < 10)
		{
			TestLed();
		}
		printf("Hello");
		Delay(100);
	}
}

void InitLed(void)
{
	GPIO_Handle_t tLedGpio = {0};

	tLedGpio.pGPIOx = GPIOA;
	tLedGpio.GpioPinConfig.GPIO_PinMode = eGPIO_OpMode;
	tLedGpio.GpioPinConfig.GPIO_PinNumber = eGPIO_PIN_5;
	tLedGpio.GpioPinConfig.GPIO_PinOpType = eGPIO_OpPushPull;
	tLedGpio.GpioPinConfig.GPIO_PinSpeed = eGPIO_LowSpeed;
	tLedGpio.GpioPinConfig.GPIO_PinPuPdCtrl = eGPIO_NoPuPd;

	GPIO_PeriClkCtrl(GPIOA, ENABLE);

	Delay(100);
	GPIO_Init(&tLedGpio);

	return;
}

void TestLed(void)
{
	GPIO_WriteToOpPin(GPIOA, eGPIO_PIN_5,eGPIOSet);
	Delay(10);
	GPIO_WriteToOpPin(GPIOA, eGPIO_PIN_5,eGPIOReset);
	Delay(10);
}

void InitUltraSonicSensor(void)
{
	GPIO_PeriClkCtrl(GPIOA, ENABLE);

	/* Initialize trigger Pin (output) */
	tUltraSonicGpio.pGPIOx = GPIOA;
	tUltraSonicGpio.GpioPinConfig.GPIO_PinMode 		= eGPIO_OpMode;
	tUltraSonicGpio.GpioPinConfig.GPIO_PinNumber 	= ucTriggerPIn;
	tUltraSonicGpio.GpioPinConfig.GPIO_PinOpType 	= eGPIO_OpPushPull;
	tUltraSonicGpio.GpioPinConfig.GPIO_PinSpeed  	= eGPIO_VeryHighSpeed;
	tUltraSonicGpio.GpioPinConfig.GPIO_PinPuPdCtrl 	= eGPIO_NoPuPd;

	GPIO_Init(&tUltraSonicGpio);

	/* Initialize trigger Pin (input) */
	tUltraSonicGpio.GpioPinConfig.GPIO_PinMode 		= eGPIO_IpMode;
	tUltraSonicGpio.GpioPinConfig.GPIO_PinNumber 	= ucEchoPin;
	tUltraSonicGpio.GpioPinConfig.GPIO_PinSpeed  	= eGPIO_VeryHighSpeed;
	tUltraSonicGpio.GpioPinConfig.GPIO_PinPuPdCtrl 	= eGPIO_Pd;

	GPIO_Init(&tUltraSonicGpio);

	return;
}

uint32_t ReadUltraSonicSensor(void)
{
    uint32_t duration = 0;
    uint32_t timeout = 25000; // Timeout after ~25ms (max sensor range is ~4ms)

    // 1. Ensure trigger is low, then wait 2us
    GPIO_WriteToOpPin(GPIOA, ucTriggerPIn, eGPIOReset);
    delay_us(2);

    // 2. Send a 10us HIGH pulse to trigger the sensor
    GPIO_WriteToOpPin(GPIOA, ucTriggerPIn, eGPIOSet);
    delay_us(10);

    GPIO_WriteToOpPin(GPIOA, ucTriggerPIn, eGPIOReset);

    // 3. Wait for the ECHO pin to go HIGH (start of pulse)
    //    This waits for the sensor to start sending the echo pulse.
    while(GPIO_ReadFromIpPin(GPIOA, ucEchoPin) == 0) {
        if (timeout-- == 0) return 0; // Sensor not responding, return 0cm
    }

    // 4. Measure the duration of the HIGH pulse on the ECHO pin
    //    Now we wait for the pin to go LOW again, counting the microseconds.
    timeout = 25000; // Reset timeout for the pulse duration
    while(GPIO_ReadFromIpPin(GPIOA, ucEchoPin) != 0) // While pin is HIGH...
    {
        duration++;       // ...increment our duration counter...
        delay_us(1);      // ...and wait 1 microsecond.
        if (duration > timeout) {
            return 0; // Pulse too long, return 0cm (timeout)
        }
    }

    // 5. Calculate distance
    // Formula: time (us) / 58 = distance (cm)
    return (duration / 58);
}

