/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>
#include <stdint.h>
#include "stm32l476xx.h"
#include "gpio.h"

#define TRIGGER_PIN
#define ECHO_PIN

void Delay(uint32_t uiMs)
{
	unsigned int i = 0, j= 0;
	for(i = 0; i < uiMs; ++i)
	{
		for(j = 0; j < 600; ++j);
	}
}

void InitLed(void);
void TestLed(void);
void InitUltraSonicSensor(void);
void ReadUltraSonicSensor(void);

int main(void)
{
	InitLed();
	while(1)
	{
		//TestLed();
		printf("Hello");
		Delay(500);
	}
}

void InitLed(void)
{
	GPIO_Handle_t tLedGpio = {0};

	tLedGpio.pGPIOx = GPIOA;
	tLedGpio.GpioPinConfig.GPIO_PinMode = eGPIO_OpMode;
	tLedGpio.GpioPinConfig.GPIO_PinNumber = eGPIO_PIN_5;
	tLedGpio.GpioPinConfig.GPIO_PinOpType = eGPIO_OpPushPull;
	tLedGpio.GpioPinConfig.GPIO_PinSpeed = eGPIO_LowSpeed;
	tLedGpio.GpioPinConfig.GPIO_PinPuPdCtrl = eGPIO_NoPuPd;

	GPIO_PeriClkCtrl(GPIOA, ENABLE);

	GPIO_Init(&tLedGpio);

	return;
}

void TestLed(void)
{
	GPIO_TogglePin(GPIOA, eGPIO_PIN_5);
}

void InitUltraSonicSensor(void)
{

}

