/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include "stm32l476xx.h"
#include "gpio.h"
#include "spi.h"
#include "i2c.h"

#define ALTERNATE_FUNCTION_4	(0x04)
#define SLAVE_ADDRESS			(0x55)


I2C_Handle_t tI2C1;

void Delay(uint32_t uiMs)
{
	unsigned int i = 0, j= 0;
	for(i = 0; i < uiMs; ++i)
	{
		for(j = 0; j < 600; ++j);
	}
}

void InitLed(void);
void TestLed(void);
void InitI2C1(void);
void InitI2C1Gpio(void);

int main(void)
{
	/* Parameter initialization. */
	uint8_t ucTxBuff[] = "Hello World\r\n";
	uint16_t uhTxLen = sizeof(ucTxBuff);

	InitLed();
	InitI2C1();

	while(1)
	{
		I2C_MasterTxData(&tI2C1, ucTxBuff, uhTxLen, SLAVE_ADDRESS);

		Delay(500);
	}
}

void InitLed(void)
{
	GPIO_Handle_t tLedGpio = {0};

	tLedGpio.pGPIOx = GPIOA;
	tLedGpio.GpioPinConfig.GPIO_PinMode = eGPIO_OpMode;
	tLedGpio.GpioPinConfig.GPIO_PinNumber = eGPIO_PIN_5;
	tLedGpio.GpioPinConfig.GPIO_PinOpType = eGPIO_OpPushPull;
	tLedGpio.GpioPinConfig.GPIO_PinSpeed = eGPIO_LowSpeed;
	tLedGpio.GpioPinConfig.GPIO_PinPuPdCtrl = eGPIO_NoPuPd;

	GPIO_PeriClkCtrl(GPIOA, ENABLE);

	Delay(100);
	GPIO_Init(&tLedGpio);

	return;
}

void TestLed(void)
{
	GPIO_WriteToOpPin(GPIOA, eGPIO_PIN_5,eGPIOSet);
	Delay(10);
	GPIO_WriteToOpPin(GPIOA, eGPIO_PIN_5,eGPIOReset);
	Delay(10);

	return;
}

void InitI2C1(void)
{
	InitI2C1Gpio();

	tI2C1.pI2Cx = I2C1;
	tI2C1.I2CConfig.I2C_AckControl = eI2cACKEn;
	tI2C1.I2CConfig.I2C_SCLSpeed = I2C_SCL_SPEED_FM;
	tI2C1.I2CConfig.I2C_DeviceAddress = 0x60;

	I2C_Init(&tI2C1);

	I2C_Enable(I2C1, ENABLE);


	return;
}

/**
 * SDA ---> PB9
 * SCL ---> PB8
 */
void InitI2C1Gpio(void)
{
	GPIO_Handle_t tI2CGpio = {0};

	tI2CGpio.pGPIOx = GPIOB;
	tI2CGpio.GpioPinConfig.GPIO_PinMode 		= eGPIO_AfMode;
	tI2CGpio.GpioPinConfig.GPIO_PinAltFunMode	= ALTERNATE_FUNCTION_4;
	tI2CGpio.GpioPinConfig.GPIO_PinOpType 		= eGPIO_OpOpenDrain;
	tI2CGpio.GpioPinConfig.GPIO_PinSpeed 		= eGPIO_VeryHighSpeed;
	tI2CGpio.GpioPinConfig.GPIO_PinPuPdCtrl 	= eGPIO_Pu;

	/* Enable Clock. */
	GPIO_PeriClkCtrl(GPIOB, ENABLE);

	/* Configure the SDA pin. */
	tI2CGpio.GpioPinConfig.GPIO_PinNumber = eGPIO_PIN_9;

	/* Initialize SDA Pin. */
	GPIO_Init(&tI2CGpio);

	/* Configure the SCL pin. */
	tI2CGpio.GpioPinConfig.GPIO_PinNumber = eGPIO_PIN_8;

	/* Initialize SCL Pin. */
	GPIO_Init(&tI2CGpio);

	return;
}

