/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>
#include <stdint.h>
#include "stm32l476xx.h"
#include "gpio.h"

void Delay(uint32_t uiMs)
{
	unsigned int i = 0, j= 0;
	for(i = 0; i < uiMs; ++i)
	{
		for(j = 0; j < 600; ++j);
	}
}

void InitLed(void);
void TestLed(void);
void InitUserButton(void);

int main(void)
{
	uint8_t ucBtnState = 0;

	InitLed();
	InitUserButton();
	while(1)
	{

		ucBtnState = GPIO_ReadFromIpPin(GPIOC, eGPIO_PIN_13);

		GPIO_WriteToOpPin(GPIOA, eGPIO_PIN_5, ucBtnState);

		Delay(10);
	}
}

void InitLed(void)
{
	GPIO_Handle_t tLedGpio = {0};

	tLedGpio.pGPIOx = GPIOA;
	tLedGpio.GpioPinConfig.GPIO_PinMode = eGPIO_OpMode;
	tLedGpio.GpioPinConfig.GPIO_PinNumber = eGPIO_PIN_5;
	tLedGpio.GpioPinConfig.GPIO_PinOpType = eGPIO_OpPushPull;
	tLedGpio.GpioPinConfig.GPIO_PinSpeed = eGPIO_LowSpeed;
	tLedGpio.GpioPinConfig.GPIO_PinPuPdCtrl = eGPIO_NoPuPd;

	GPIO_PeriClkCtrl(GPIOA, ENABLE);

	Delay(100);
	GPIO_Init(&tLedGpio);

	return;
}

void TestLed(void)
{
	GPIO_WriteToOpPin(GPIOA, eGPIO_PIN_5,eGPIOSet);
	Delay(10);
	GPIO_WriteToOpPin(GPIOA, eGPIO_PIN_5,eGPIOReset);
	Delay(10);

	return;
}

void InitUserButton(void)
{
	GPIO_Handle_t tBtnGpio = {0};

	tBtnGpio.pGPIOx = GPIOC;
	tBtnGpio.GpioPinConfig.GPIO_PinMode = eGPIO_IpMode;
	tBtnGpio.GpioPinConfig.GPIO_PinNumber = eGPIO_PIN_13;
	tBtnGpio.GpioPinConfig.GPIO_PinOpType = eGPIO_OpPushPull;
	tBtnGpio.GpioPinConfig.GPIO_PinSpeed = eGPIO_LowSpeed;
	tBtnGpio.GpioPinConfig.GPIO_PinPuPdCtrl = eGPIO_NoPuPd;

	GPIO_PeriClkCtrl(GPIOC, ENABLE);

	Delay(100);
	GPIO_Init(&tBtnGpio);

	return;
}

