/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include "stm32l476xx.h"
#include "gpio.h"
#include "spi.h"

#define ALTERNATE_FUNCTION_5	(0x05)
uint8_t ucTxBuff[] = "Hello World\r\n";
uint8_t ucRxBuff[100] = {0};
uint16_t uhBuffSize = sizeof(ucTxBuff);

void Delay(uint32_t uiMs)
{
	unsigned int i = 0, j= 0;
	for(i = 0; i < uiMs; ++i)
	{
		for(j = 0; j < 600; ++j);
	}
}

void InitLed(void);
void InitSpi1Gpio(void);
void IntSpi1(void);
void TestLed(void);

SPI_Handle_t Spi1Handle;

int main(void)
{
	/* Parameter initialization. */
	InitLed();
	IntSpi1();

	SPI_IRQConfig(SPI1_IRQn, ENABLE);

	/* Enable SPI. */
	SPI_Enable(SPI1, ENABLE);

	//SPI_TxDataIT(&Spi1Handle, ucTxBuff, uhBuffSize);
	//SPI_RxDataIT(&Spi1Handle, ucRxBuff, uhBuffSize);
	//SPI_TransmitReceiveIT(&Spi1Handle, ucTxBuff, ucRxBuff, uhBuffSize);

	while(1)
	{
		printf("Hello world\n");

		if(memcmp(ucTxBuff, ucRxBuff, uhBuffSize) == 0)
		{

			/* Disable SPI. */
			SPI_Enable(SPI1, DISABLE);
		}

		Delay(100);
	}
}

void InitLed(void)
{
	GPIO_Handle_t tLedGpio = {0};

	tLedGpio.pGPIOx = GPIOA;
	tLedGpio.GpioPinConfig.GPIO_PinMode = eGPIO_OpMode;
	tLedGpio.GpioPinConfig.GPIO_PinNumber = eGPIO_PIN_5;
	tLedGpio.GpioPinConfig.GPIO_PinOpType = eGPIO_OpPushPull;
	tLedGpio.GpioPinConfig.GPIO_PinSpeed = eGPIO_LowSpeed;
	tLedGpio.GpioPinConfig.GPIO_PinPuPdCtrl = eGPIO_NoPuPd;

	GPIO_PeriClkCtrl(GPIOA, ENABLE);

	Delay(100);
	GPIO_Init(&tLedGpio);

	return;
}

void TestLed(void)
{
	GPIO_WriteToOpPin(GPIOA, eGPIO_PIN_5,eGPIOSet);
	Delay(10);
	GPIO_WriteToOpPin(GPIOA, eGPIO_PIN_5,eGPIOReset);
	Delay(10);

	return;
}


/*
 * MISO ---> PA6
 * MOSI ---> PA7
 * CLK  ---> PA5
 * NSS	---> PA4
 */
void InitSpi1Gpio(void)
{
	GPIO_Handle_t Spi1Gpio = {0};


	GPIO_PeriClkCtrl(GPIOA, ENABLE);

	/* MISO Initialization. */
	Spi1Gpio.pGPIOx = GPIOA;
	Spi1Gpio.GpioPinConfig.GPIO_PinMode 		= eGPIO_AfMode;
	Spi1Gpio.GpioPinConfig.GPIO_PinSpeed		= eGPIO_VeryHighSpeed;
	Spi1Gpio.GpioPinConfig.GPIO_PinPuPdCtrl 	= eGPIO_NoPuPd;
	Spi1Gpio.GpioPinConfig.GPIO_PinOpType 		= eGPIO_OpPushPull;
	Spi1Gpio.GpioPinConfig.GPIO_PinAltFunMode 	= ALTERNATE_FUNCTION_5;


	Spi1Gpio.GpioPinConfig.GPIO_PinNumber 		= eGPIO_PIN_6;
	GPIO_Init(&Spi1Gpio);

	/* MOSI Initialization. */
	Spi1Gpio.GpioPinConfig.GPIO_PinNumber 		= eGPIO_PIN_7;
	GPIO_Init(&Spi1Gpio);

	/* SCK Initialization. */
	Spi1Gpio.GpioPinConfig.GPIO_PinNumber 		= eGPIO_PIN_5;
	GPIO_Init(&Spi1Gpio);

	/* NSS Initialization. */
	Spi1Gpio.GpioPinConfig.GPIO_PinNumber 		= eGPIO_PIN_4;
	GPIO_Init(&Spi1Gpio);

	return;
}

void IntSpi1(void)
{

	/* Initialize the SPI1 GPIO. */
	InitSpi1Gpio();

	/* Enable Clock. */
	SPI_PclkCtrl(SPI1, ENABLE);


	/* Configure SPI1. */
	Spi1Handle.pSPIx = SPI1;
	Spi1Handle.SPIConfig.SPI_BusConfig = eSPIBusConfigFullDuplex;
	Spi1Handle.SPIConfig.SPI_CPHA = eSPICphaseState0;
	Spi1Handle.SPIConfig.SPI_CPOL = eSPICpolState0;
	Spi1Handle.SPIConfig.SPI_DFF = eSPIDff8Bits;
	Spi1Handle.SPIConfig.SPI_DeviceMode = eSPIModeMaster;
	Spi1Handle.SPIConfig.SPI_SclkSpeed = eSpiSclkDiv2;
	Spi1Handle.SPIConfig.SPI_SSM = eSsmSwEn;
	Spi1Handle.pucTxBuff = ucTxBuff;
	Spi1Handle.pucRxBuff = ucRxBuff;
	Spi1Handle.uhRxLen = uhBuffSize;
	Spi1Handle.uhTxLen = uhBuffSize;

	/* Initialize SPI. */
	SPI_Init(&Spi1Handle);

	/* SPOI SSI Config. */
	SPI_SsiConfig(SPI1, ENABLE);

	return;
}

void SPI1_IRQHandler(void)
{
	SPI_IRQHandling(&Spi1Handle);
	return;
}


