/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include "stm32l476xx.h"
#include "gpio.h"
#include "spi.h"
#include "i2c.h"
#include "uart.h"

#define ALTERNATE_FUNCTION_7	(0x07)
#define SLAVE_ADDRESS			(0x55)

/* Parameter initialization. */
uint8_t ucTxBuff[] = "Hello World\r\n";
uint16_t uhTxLen = sizeof(ucTxBuff);
uint8_t ucRxBuff[100] = {0};
uint8_t ucUarttxBuff[100];

void Delay(uint32_t uiMs)
{
	unsigned int i = 0, j= 0;
	for(i = 0; i < uiMs; ++i)
	{
		for(j = 0; j < 600; ++j);
	}
}

void InitLed(void);
void TestLed(void);
void InitUartGpio(void);
void InitUart(void);

USART_Handle_t tUart2;

int main(void)
{
	InitUart();

	//USART_TxDataIT(&tUart2, ucTxBuff, uhTxLen);
	USART_RxDataIT(&tUart2,ucRxBuff, 6);

	while(1)
	{
		Delay(500);
	}
}

void InitLed(void)
{
	GPIO_Handle_t tLedGpio = {0};

	tLedGpio.pGPIOx = GPIOA;
	tLedGpio.GpioPinConfig.GPIO_PinMode = eGPIO_OpMode;
	tLedGpio.GpioPinConfig.GPIO_PinNumber = eGPIO_PIN_5;
	tLedGpio.GpioPinConfig.GPIO_PinOpType = eGPIO_OpPushPull;
	tLedGpio.GpioPinConfig.GPIO_PinSpeed = eGPIO_LowSpeed;
	tLedGpio.GpioPinConfig.GPIO_PinPuPdCtrl = eGPIO_NoPuPd;

	GPIO_PeriClkCtrl(GPIOA, ENABLE);

	Delay(100);
	GPIO_Init(&tLedGpio);

	return;
}

void TestLed(void)
{
	GPIO_WriteToOpPin(GPIOA, eGPIO_PIN_5,eGPIOSet);
	Delay(10);
	GPIO_WriteToOpPin(GPIOA, eGPIO_PIN_5,eGPIOReset);
	Delay(10);

	return;
}

void InitUartGpio(void)
{
	GPIO_Handle_t tUartGpio = {0};

	tUartGpio.pGPIOx = GPIOA;
	tUartGpio.GpioPinConfig.GPIO_PinMode = eGPIO_AfMode;
	tUartGpio.GpioPinConfig.GPIO_PinOpType = eGPIO_OpPushPull;
	tUartGpio.GpioPinConfig.GPIO_PinSpeed = eGPIO_VeryHighSpeed;
	tUartGpio.GpioPinConfig.GPIO_PinPuPdCtrl = eGPIO_NoPuPd;
	tUartGpio.GpioPinConfig.GPIO_PinAltFunMode = ALTERNATE_FUNCTION_7;

	GPIO_PeriClkCtrl(GPIOA, ENABLE);

	/* Configure TX pin. */
	tUartGpio.GpioPinConfig.GPIO_PinNumber = eGPIO_PIN_2;
	GPIO_Init(&tUartGpio);

	/* Configure RX pin. */
	tUartGpio.GpioPinConfig.GPIO_PinNumber = eGPIO_PIN_3;
	GPIO_Init(&tUartGpio);

	return;
}

void InitUart(void)
{
	/* Initialize UART GPIO. */
	InitUartGpio();

	tUart2.pUSARTx = USART2;
	tUart2.USARTConfig.USART_Baud = USART_BAUD_115200;
	tUart2.USARTConfig.USART_HwFlowControl = eUsartHwFlwCtrlNone;
	tUart2.USARTConfig.USART_Mode = eUsartModeTxRx;
	tUart2.USARTConfig.USART_NoOfStopBits = eUsartStopBit1;
	tUart2.USARTConfig.USART_ParityControl = eUsartParityNone;
	tUart2.USARTConfig.USART_WordLength = eUsartWordLen8Bits;
//	tUart2.pucTxBuffer = ucTxBuff;
//	tUart2.uhTxLen = uhTxLen;
//	tUart2.ucTxBsyState = eUsartStateReady;

	USART_IRQConfig(USART2_IRQn, ENABLE);

	USART_IRQPriorityConfig(USART2_IRQn, 2);

	/* Initialize USART2. */
	USART_Init(&tUart2);

	/* Enable USART2. */
	USART_PeripheralControl(USART2, ENABLE);

	return;
}

void USART2_IRQHandler(void)
{
	USART_IRQHandling(&tUart2);
}

